---
scope/components:
  - src/components/**/*
scope/utils:
  - src/utils/**/*
scope/ci:
  - .github/**/*
  - build/**/*
scope/storybook:
  - .storybook/**/*
scope/js:
  - ./**/*.js
scope/css:
  - ./**/*.css
  - ./**/*.scss