---
name: label-diff

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  paths:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v3
        with:
          configuration-path: .github/labeler-paths.yml
          repo-token: ${{ secrets.GITHUB_TOKEN }}